import type { ShortcutManifestEntry } from '@labre/std';

/**
 * The UML commands as SHORTCUT-MANIFEST rows — id, label, chord, scope,
 * owner — and nothing else.
 *
 * DATA ONLY, and that is the whole point (`docs/adr/0008` § Packaging). A
 * `CommandDescriptor` carries its `run`, so a host settings pane that imported
 * the package entry to list names and chords would drag the entire action graph
 * — the grammar, the XMI and PlantUML writers, the surface and gfx deep paths —
 * into its chunk. This module has type-only imports, so the published bundle
 * exposes it as `./commands-manifest`: a few hundred bytes that reference
 * nothing.
 *
 * GENERATED-SHAPED, hand-committed: `commands-manifest.unit.spec.ts` asserts
 * row-for-row equality with `toShortcutManifestEntry` over `umlCommands`, so
 * this file cannot drift from the commands it projects. Add a command and the
 * test says exactly what to add here.
 */
export const umlCommandsManifest: ShortcutManifestEntry[] = [
  {
    id: 'uml.addDiagram',
    owner: 'uml',
    labelKey: 'com.labre.commands.uml.addDiagram',
    labelFallback: 'UML diagram',
    scope: 'edgeless',
    defaultKeys: { mac: [], other: [] },
  },
  {
    id: 'uml.addClass',
    owner: 'uml',
    labelKey: 'com.labre.commands.uml.addClass',
    labelFallback: 'Class',
    scope: 'edgeless',
    defaultKeys: { mac: [], other: [] },
  },
  {
    id: 'uml.addInterface',
    owner: 'uml',
    labelKey: 'com.labre.commands.uml.addInterface',
    labelFallback: 'Interface',
    scope: 'edgeless',
    defaultKeys: { mac: [], other: [] },
  },
  {
    id: 'uml.addEnumeration',
    owner: 'uml',
    labelKey: 'com.labre.commands.uml.addEnumeration',
    labelFallback: 'Enumeration',
    scope: 'edgeless',
    defaultKeys: { mac: [], other: [] },
  },
  {
    id: 'uml.addPackage',
    owner: 'uml',
    labelKey: 'com.labre.commands.uml.addPackage',
    labelFallback: 'Package',
    scope: 'edgeless',
    defaultKeys: { mac: [], other: [] },
  },
  {
    id: 'uml.addActor',
    owner: 'uml',
    labelKey: 'com.labre.commands.uml.addActor',
    labelFallback: 'Actor',
    scope: 'edgeless',
    defaultKeys: { mac: [], other: [] },
  },
  {
    id: 'uml.addUseCase',
    owner: 'uml',
    labelKey: 'com.labre.commands.uml.addUseCase',
    labelFallback: 'Use case',
    scope: 'edgeless',
    defaultKeys: { mac: [], other: [] },
  },
  {
    id: 'uml.addSubject',
    owner: 'uml',
    labelKey: 'com.labre.commands.uml.addSubject',
    labelFallback: 'Subject',
    scope: 'edgeless',
    defaultKeys: { mac: [], other: [] },
  },
  {
    id: 'uml.addObject',
    owner: 'uml',
    labelKey: 'com.labre.commands.uml.addObject',
    labelFallback: 'Object',
    scope: 'edgeless',
    defaultKeys: { mac: [], other: [] },
  },
  {
    id: 'uml.associationTool',
    owner: 'uml',
    labelKey: 'com.labre.commands.uml.associationTool',
    labelFallback: 'Association',
    scope: 'edgeless',
    defaultKeys: { mac: [], other: [] },
  },
  {
    id: 'uml.addNote',
    owner: 'uml',
    labelKey: 'com.labre.commands.uml.addNote',
    labelFallback: 'Note',
    scope: 'edgeless',
    defaultKeys: { mac: [], other: [] },
  },
  {
    id: 'uml.generalizationTool',
    owner: 'uml',
    labelKey: 'com.labre.commands.uml.generalizationTool',
    labelFallback: 'Generalization',
    scope: 'edgeless',
    defaultKeys: { mac: [], other: [] },
  },
  {
    id: 'uml.dependencyTool',
    owner: 'uml',
    labelKey: 'com.labre.commands.uml.dependencyTool',
    labelFallback: 'Dependency',
    scope: 'edgeless',
    defaultKeys: { mac: [], other: [] },
  },
  {
    id: 'uml.includeTool',
    owner: 'uml',
    labelKey: 'com.labre.commands.uml.includeTool',
    labelFallback: 'Include',
    scope: 'edgeless',
    defaultKeys: { mac: [], other: [] },
  },
  {
    id: 'uml.extendTool',
    owner: 'uml',
    labelKey: 'com.labre.commands.uml.extendTool',
    labelFallback: 'Extend',
    scope: 'edgeless',
    defaultKeys: { mac: [], other: [] },
  },
  {
    id: 'uml.aggregationTool',
    owner: 'uml',
    labelKey: 'com.labre.commands.uml.aggregationTool',
    labelFallback: 'Aggregation',
    scope: 'edgeless',
    defaultKeys: { mac: [], other: [] },
  },
  {
    id: 'uml.compositionTool',
    owner: 'uml',
    labelKey: 'com.labre.commands.uml.compositionTool',
    labelFallback: 'Composition',
    scope: 'edgeless',
    defaultKeys: { mac: [], other: [] },
  },
  {
    id: 'uml.realizationTool',
    owner: 'uml',
    labelKey: 'com.labre.commands.uml.realizationTool',
    labelFallback: 'Realization',
    scope: 'edgeless',
    defaultKeys: { mac: [], other: [] },
  },
  {
    id: 'uml.anchorTool',
    owner: 'uml',
    labelKey: 'com.labre.commands.uml.anchorTool',
    labelFallback: 'Anchor',
    scope: 'edgeless',
    defaultKeys: { mac: [], other: [] },
  },
  {
    id: 'uml.addComponent',
    owner: 'uml',
    labelKey: 'com.labre.commands.uml.addComponent',
    labelFallback: 'Component',
    scope: 'edgeless',
    defaultKeys: { mac: [], other: [] },
  },
  {
    id: 'uml.addPort',
    owner: 'uml',
    labelKey: 'com.labre.commands.uml.addPort',
    labelFallback: 'Port',
    scope: 'edgeless',
    defaultKeys: { mac: [], other: [] },
  },
  {
    id: 'uml.addProvidedInterface',
    owner: 'uml',
    labelKey: 'com.labre.commands.uml.addProvidedInterface',
    labelFallback: 'Provided interface',
    scope: 'edgeless',
    defaultKeys: { mac: [], other: [] },
  },
  {
    id: 'uml.addRequiredInterface',
    owner: 'uml',
    labelKey: 'com.labre.commands.uml.addRequiredInterface',
    labelFallback: 'Required interface',
    scope: 'edgeless',
    defaultKeys: { mac: [], other: [] },
  },
  {
    id: 'uml.addArtifact',
    owner: 'uml',
    labelKey: 'com.labre.commands.uml.addArtifact',
    labelFallback: 'Artifact',
    scope: 'edgeless',
    defaultKeys: { mac: [], other: [] },
  },
  {
    id: 'uml.addNode',
    owner: 'uml',
    labelKey: 'com.labre.commands.uml.addNode',
    labelFallback: 'Node',
    scope: 'edgeless',
    defaultKeys: { mac: [], other: [] },
  },
  {
    id: 'uml.addDevice',
    owner: 'uml',
    labelKey: 'com.labre.commands.uml.addDevice',
    labelFallback: 'Device',
    scope: 'edgeless',
    defaultKeys: { mac: [], other: [] },
  },
  {
    id: 'uml.addExecutionEnvironment',
    owner: 'uml',
    labelKey: 'com.labre.commands.uml.addExecutionEnvironment',
    labelFallback: 'Execution environment',
    scope: 'edgeless',
    defaultKeys: { mac: [], other: [] },
  },
  {
    id: 'uml.deployTool',
    owner: 'uml',
    labelKey: 'com.labre.commands.uml.deployTool',
    labelFallback: 'Deploy',
    scope: 'edgeless',
    defaultKeys: { mac: [], other: [] },
  },
  {
    id: 'uml.manifestTool',
    owner: 'uml',
    labelKey: 'com.labre.commands.uml.manifestTool',
    labelFallback: 'Manifest',
    scope: 'edgeless',
    defaultKeys: { mac: [], other: [] },
  },
  {
    id: 'uml.communicationPathTool',
    owner: 'uml',
    labelKey: 'com.labre.commands.uml.communicationPathTool',
    labelFallback: 'Communication path',
    scope: 'edgeless',
    defaultKeys: { mac: [], other: [] },
  },
  {
    id: 'uml.addAction',
    owner: 'uml',
    labelKey: 'com.labre.commands.uml.addAction',
    labelFallback: 'Action',
    scope: 'edgeless',
    defaultKeys: { mac: [], other: [] },
  },
  {
    id: 'uml.addInitial',
    owner: 'uml',
    labelKey: 'com.labre.commands.uml.addInitial',
    labelFallback: 'Initial node',
    scope: 'edgeless',
    defaultKeys: { mac: [], other: [] },
  },
  {
    id: 'uml.addActivityFinal',
    owner: 'uml',
    labelKey: 'com.labre.commands.uml.addActivityFinal',
    labelFallback: 'Activity final',
    scope: 'edgeless',
    defaultKeys: { mac: [], other: [] },
  },
  {
    id: 'uml.addFlowFinal',
    owner: 'uml',
    labelKey: 'com.labre.commands.uml.addFlowFinal',
    labelFallback: 'Flow final',
    scope: 'edgeless',
    defaultKeys: { mac: [], other: [] },
  },
  {
    id: 'uml.addDecision',
    owner: 'uml',
    labelKey: 'com.labre.commands.uml.addDecision',
    labelFallback: 'Decision',
    scope: 'edgeless',
    defaultKeys: { mac: [], other: [] },
  },
  {
    id: 'uml.addFork',
    owner: 'uml',
    labelKey: 'com.labre.commands.uml.addFork',
    labelFallback: 'Fork',
    scope: 'edgeless',
    defaultKeys: { mac: [], other: [] },
  },
  {
    id: 'uml.addObjectNode',
    owner: 'uml',
    labelKey: 'com.labre.commands.uml.addObjectNode',
    labelFallback: 'Object node',
    scope: 'edgeless',
    defaultKeys: { mac: [], other: [] },
  },
  {
    id: 'uml.addSendSignal',
    owner: 'uml',
    labelKey: 'com.labre.commands.uml.addSendSignal',
    labelFallback: 'Send signal',
    scope: 'edgeless',
    defaultKeys: { mac: [], other: [] },
  },
  {
    id: 'uml.addAcceptEvent',
    owner: 'uml',
    labelKey: 'com.labre.commands.uml.addAcceptEvent',
    labelFallback: 'Accept event',
    scope: 'edgeless',
    defaultKeys: { mac: [], other: [] },
  },
  {
    id: 'uml.addTimeEvent',
    owner: 'uml',
    labelKey: 'com.labre.commands.uml.addTimeEvent',
    labelFallback: 'Time event',
    scope: 'edgeless',
    defaultKeys: { mac: [], other: [] },
  },
  {
    id: 'uml.addPartition',
    owner: 'uml',
    labelKey: 'com.labre.commands.uml.addPartition',
    labelFallback: 'Partition',
    scope: 'edgeless',
    defaultKeys: { mac: [], other: [] },
  },
  {
    id: 'uml.controlFlowTool',
    owner: 'uml',
    labelKey: 'com.labre.commands.uml.controlFlowTool',
    labelFallback: 'Control flow',
    scope: 'edgeless',
    defaultKeys: { mac: [], other: [] },
  },
  {
    id: 'uml.objectFlowTool',
    owner: 'uml',
    labelKey: 'com.labre.commands.uml.objectFlowTool',
    labelFallback: 'Object flow',
    scope: 'edgeless',
    defaultKeys: { mac: [], other: [] },
  },
  {
    id: 'uml.addState',
    owner: 'uml',
    labelKey: 'com.labre.commands.uml.addState',
    labelFallback: 'State',
    scope: 'edgeless',
    defaultKeys: { mac: [], other: [] },
  },
  {
    id: 'uml.addFinalState',
    owner: 'uml',
    labelKey: 'com.labre.commands.uml.addFinalState',
    labelFallback: 'Final state',
    scope: 'edgeless',
    defaultKeys: { mac: [], other: [] },
  },
  {
    id: 'uml.addChoice',
    owner: 'uml',
    labelKey: 'com.labre.commands.uml.addChoice',
    labelFallback: 'Choice',
    scope: 'edgeless',
    defaultKeys: { mac: [], other: [] },
  },
  {
    id: 'uml.addJunction',
    owner: 'uml',
    labelKey: 'com.labre.commands.uml.addJunction',
    labelFallback: 'Junction',
    scope: 'edgeless',
    defaultKeys: { mac: [], other: [] },
  },
  {
    id: 'uml.addShallowHistory',
    owner: 'uml',
    labelKey: 'com.labre.commands.uml.addShallowHistory',
    labelFallback: 'Shallow history',
    scope: 'edgeless',
    defaultKeys: { mac: [], other: [] },
  },
  {
    id: 'uml.addDeepHistory',
    owner: 'uml',
    labelKey: 'com.labre.commands.uml.addDeepHistory',
    labelFallback: 'Deep history',
    scope: 'edgeless',
    defaultKeys: { mac: [], other: [] },
  },
  {
    id: 'uml.addEntryPoint',
    owner: 'uml',
    labelKey: 'com.labre.commands.uml.addEntryPoint',
    labelFallback: 'Entry point',
    scope: 'edgeless',
    defaultKeys: { mac: [], other: [] },
  },
  {
    id: 'uml.addExitPoint',
    owner: 'uml',
    labelKey: 'com.labre.commands.uml.addExitPoint',
    labelFallback: 'Exit point',
    scope: 'edgeless',
    defaultKeys: { mac: [], other: [] },
  },
  {
    id: 'uml.addTerminate',
    owner: 'uml',
    labelKey: 'com.labre.commands.uml.addTerminate',
    labelFallback: 'Terminate',
    scope: 'edgeless',
    defaultKeys: { mac: [], other: [] },
  },
  {
    id: 'uml.addRegion',
    owner: 'uml',
    labelKey: 'com.labre.commands.uml.addRegion',
    labelFallback: 'Region',
    scope: 'edgeless',
    defaultKeys: { mac: [], other: [] },
  },
  {
    id: 'uml.transitionTool',
    owner: 'uml',
    labelKey: 'com.labre.commands.uml.transitionTool',
    labelFallback: 'Transition',
    scope: 'edgeless',
    defaultKeys: { mac: [], other: [] },
  },
  {
    id: 'uml.addLifeline',
    owner: 'uml',
    labelKey: 'com.labre.commands.uml.addLifeline',
    labelFallback: 'Lifeline',
    scope: 'edgeless',
    defaultKeys: { mac: [], other: [] },
  },
  {
    id: 'uml.addExecution',
    owner: 'uml',
    labelKey: 'com.labre.commands.uml.addExecution',
    labelFallback: 'Execution',
    scope: 'edgeless',
    defaultKeys: { mac: [], other: [] },
  },
  {
    id: 'uml.addDestruction',
    owner: 'uml',
    labelKey: 'com.labre.commands.uml.addDestruction',
    labelFallback: 'Destruction',
    scope: 'edgeless',
    defaultKeys: { mac: [], other: [] },
  },
  {
    id: 'uml.addFragment',
    owner: 'uml',
    labelKey: 'com.labre.commands.uml.addFragment',
    labelFallback: 'Combined fragment',
    scope: 'edgeless',
    defaultKeys: { mac: [], other: [] },
  },
  {
    id: 'uml.addInteractionUse',
    owner: 'uml',
    labelKey: 'com.labre.commands.uml.addInteractionUse',
    labelFallback: 'Interaction use',
    scope: 'edgeless',
    defaultKeys: { mac: [], other: [] },
  },
  {
    id: 'uml.messageSyncTool',
    owner: 'uml',
    labelKey: 'com.labre.commands.uml.messageSyncTool',
    labelFallback: 'Synchronous message',
    scope: 'edgeless',
    defaultKeys: { mac: [], other: [] },
  },
  {
    id: 'uml.messageAsyncTool',
    owner: 'uml',
    labelKey: 'com.labre.commands.uml.messageAsyncTool',
    labelFallback: 'Asynchronous message',
    scope: 'edgeless',
    defaultKeys: { mac: [], other: [] },
  },
  {
    id: 'uml.messageReplyTool',
    owner: 'uml',
    labelKey: 'com.labre.commands.uml.messageReplyTool',
    labelFallback: 'Reply message',
    scope: 'edgeless',
    defaultKeys: { mac: [], other: [] },
  },
  {
    id: 'uml.messageCreateTool',
    owner: 'uml',
    labelKey: 'com.labre.commands.uml.messageCreateTool',
    labelFallback: 'Create message',
    scope: 'edgeless',
    defaultKeys: { mac: [], other: [] },
  },
  {
    id: 'uml.messageDeleteTool',
    owner: 'uml',
    labelKey: 'com.labre.commands.uml.messageDeleteTool',
    labelFallback: 'Delete message',
    scope: 'edgeless',
    defaultKeys: { mac: [], other: [] },
  },
  {
    id: 'uml.exportPlantuml',
    owner: 'uml',
    labelKey: 'com.labre.commands.uml.exportPlantuml',
    labelFallback: 'Export as PlantUML',
    scope: 'edgeless',
    defaultKeys: { mac: [], other: [] },
  },
  {
    id: 'uml.exportXmi',
    owner: 'uml',
    labelKey: 'com.labre.commands.uml.exportXmi',
    labelFallback: 'Export as XMI',
    scope: 'edgeless',
    defaultKeys: { mac: [], other: [] },
  },
  {
    id: 'uml.importXmi',
    owner: 'uml',
    labelKey: 'com.labre.commands.uml.importXmi',
    labelFallback: 'Import XMI',
    scope: 'edgeless',
    defaultKeys: { mac: [], other: [] },
  },
  {
    id: 'uml.importPlantuml',
    owner: 'uml',
    labelKey: 'com.labre.commands.uml.importPlantuml',
    labelFallback: 'Import PlantUML',
    scope: 'edgeless',
    defaultKeys: { mac: [], other: [] },
  },
  {
    id: 'uml.importDrawio',
    owner: 'uml',
    labelKey: 'com.labre.commands.uml.importDrawio',
    labelFallback: 'Import draw.io drawing',
    scope: 'edgeless',
    defaultKeys: { mac: [], other: [] },
  },
];
